### ISSUE TITLE
Feed xml

### ISSUE THREAD

**Issue by gianarb** [gianarb/gianarb.github.com#6]
Add feed xml

feedback by @lmammino
Thanks

**Comment by lmammino** [comment]
Wow I noticed the issue just now. I don't know why I expected you had a PHP website (something self made with silex, zend or symfony). 
I don't know Jekyll but your solution seems really effective and simple ;) well done!

**Comment by gianarb** [comment]
Jekyll is a good platform to manage static website :+1: try it! :) Good works
